#!/usr/bin/perl

use strict;

my $epsilon = 1e-10;

my $work_weight     = 0.0964037;
my $work_exp        = 0.379919;
my $home_exp        = 0.739806;
my $retail_weight   = 43.8294;
my $retail_exp      = 1.48386;
my $accomm_weight   = 7.14946;
my $accomm_exp      = 0.965433;
my $school_weight   = 0.86146;
my $school_exp      = 0.774459;
my $teach_weight    = 0.27613;
my $teach_exp       = 0.729509;
my $blocks_exp      = 0.223233;
my $scale           = 2.20189;
my $intercept       = 8.88599e+06;

sub fpow {
	my ($base, $exp) = @_;

	if ($base == 0) {
		return 0;
	}

	return exp(log($base) * $exp);
}

sub f {
	my ($area, $work, $home, $retail, $accomm, $school, $teach, $split, $blocks) = @_;

	return abs($intercept) *
        fpow($blocks / $area, abs($blocks_exp)) *
        fpow(
                (
                        $work_weight * fpow($work / $area, abs($work_exp)) +
                        fpow($home / $area, abs($home_exp)) +
                        $retail_weight * fpow($retail / $area, abs($retail_exp)) +
                        $accomm_weight * fpow($accomm / $area, abs($accomm_exp)) +
                        $school_weight * fpow($school / 200, abs($school_exp)) +
                        $teach_weight * fpow($teach / $area, abs($teach_exp)) +
                        0
                ),
	abs($scale));
}

while (<>) {
	chomp;
	my @fields = split(/ /);

	my $actual = ($fields[0]);
	my $model = (f($fields[55], $fields[1], $fields[57], $fields[14], $fields[25], $fields[61], $fields[22], $fields[60], $fields[59]));

	printf("%.6f ", $actual / $model);
	print "$actual $model $fields[67]\n";
}
