#!/usr/bin/perl

use strict;

my $work_weight     = 0.0582971;
my $work_exp        = 0.413058;
my $home_exp        = 0.839656;
my $retail_weight   = 49.8593;
my $retail_exp      = 1.548;
my $accomm_weight   = 3.00466;
my $accomm_exp      = 0.91199;
my $school_weight   = 0.246916;
my $school_exp      = 0.688558;
my $teach_weight    = 0.29323;
my $teach_exp       = 0.716993;
my $stops_weight    = 57.0325;
my $stops_exp       = 0.892148;
my $blocks_exp      = 0.132785;
my $scale           = 1.78344;
my $intercept       = 1.5337e+06;

sub fpow {
	my ($base, $exp) = @_;

	if ($base == 0) {
		return 0;
	}

	return exp(log($base) * $exp);
}

sub f {
	my ($area, $work, $home, $retail, $accomm, $school, $teach, $split, $blocks, $stops) = @_;

	return abs($intercept) *
        fpow($blocks / $area, abs($blocks_exp)) *
	(1 + abs($stops_weight) * fpow($stops, abs($stops_exp))) *
        fpow(
                (
                        $work_weight * fpow($work / $area, abs($work_exp)) +
                        fpow($home / $area, abs($home_exp)) +
                        $retail_weight * fpow($retail / $area, abs($retail_exp)) +
                        $accomm_weight * fpow($accomm / $area, abs($accomm_exp)) +
                        $school_weight * fpow($school / 200, abs($school_exp)) +
                        $teach_weight * fpow($teach / $area, abs($teach_exp)) +
                        0
                ),
	abs($scale));
}

while (<>) {
	chomp;
	my @fields = split(/ /);

	my $actual = ($fields[0]);
	my $model = (f($fields[55], $fields[1], $fields[57], $fields[14], $fields[25], $fields[61], $fields[22], $fields[60], $fields[59], $fields[67]));

	printf("%.6f ", $actual / $model);
	print "$actual $model $fields[68]\n";
}
