#!/usr/bin/perl

use strict;

my $epsilon = 1e-10;

my $work_weight     = 0.621569;
my $work_exp        = 1.05523;
my $home_exp        = 1.35907;
my $retail_weight   = 4.91751;
my $retail_exp      = 2.89947;
my $accomm_weight   = 10.2007;
my $accomm_exp      = 1.20083;
my $school_weight   = 1.59076;
my $school_exp      = 1.08525;
my $teach_weight    = 1.7561;
my $teach_exp       = 0.969141;
my $intercept       = 5.47161;

sub fpow {
	my ($base, $exp) = @_;

	if ($base == 0) {
		return 0;
	}

	return exp(log($base) * $exp);
}

sub f {
	my ($work, $home, $retail, $accomm, $school, $teach) = @_;

	return
        log(
                abs($work_weight) * fpow(exp($work), $work_exp) +
                fpow(exp($home), $home_exp) +
                abs($retail_weight) * fpow(exp($retail), $retail_exp) +
                abs($accomm_weight) * fpow(exp($accomm), $accomm_exp) +
                abs($school_weight) * fpow(exp($school), $school_exp) +
                abs($teach_weight) * fpow(exp($teach), $teach_exp) +
	0) +
        $intercept;
}

while (<>) {
	chomp;
	my @fields = split(/ /);

	my $actual = ($fields[0]);
	my $model = exp(f(log($fields[1] + $epsilon), log($fields[57] + $epsilon), log($fields[14] + $epsilon), log($fields[25] + $epsilon), log($fields[61] + $epsilon), log($fields[22] + $epsilon)));

	printf("%.6f ", $actual / $model);
	print "$actual $model $fields[62]\n";
}
