#!/usr/bin/perl

$pi = 4 * atan2(1, 1);
$foot = .00000274;
$bucket = 5280 * $foot;

$| = 1;

open(IN, "daily.csv");
while (<IN>) {
	chomp;
	($id, $name, $id2, $date, $time, @fields) = split(/,/);
	next if $fields[20] eq "";

	$lat = $fields[20];
	$lon = $fields[21];
	$walk = $fields[12] + $fields[13] + $fields[14] + $fields[15];

	next if $walk == 0;

	if ($walk > $walk{"$lat,$lon"}) {
		$walk{"$lat,$lon"} = $walk;
	}

	$a = int($lat / $bucket);
	$o = int($lon / $bucket);

	push @{$near{$a}{$o}}, "$lat,$lon";
}
close(IN);

open(IN, "all-employment");
while (<IN>) {
	chomp;
	@fields = split(/,/);

	($lat, $lon) = ($fields[53], $fields[54]);

	$a = int($lat / $bucket);
	$o = int($lon / $bucket);

	@candidates = ();
	for ($aa = $a - 1; $aa <= $a + 1; $aa++) {
		for ($oo = $o - 1; $oo <= $o + 1; $oo++) {
			push @candidates, @{$near{$aa}{$oo}};
		}
	}

	if ($seq++ % 10000 == 0) {
		printf STDERR ("%.2f\r", $seq / 6595711 * 100);
	}

	if ($#candidates >= 0) {
		$rat = cos($lat * $pi / 180);

		for $cand (@candidates) {
			($lat2, $lon2) = split(/,/, $cand);

			$latd = $lat2 - $lat;
			$lond = ($lon2 - $lon) * $rat;
			$d = sqrt($latd * $latd + $lond * $lond);

			if ($d < $bucket) {
				$d = int($d / $foot);

				for $radius (1320) {
					if ($d < $radius) {
						for $field (2, 58) {
							$sum{$cand}{$field}{$radius} += $fields[$field - 1];
						}
						$count{$cand}{$radius} += 1;
					}
				}
			}
		}
	}
}

for $where (keys(%sum)) {
	printf("%s %d", $where, $walk{$where});

	for $radius (1320) {
		$scale = 1320 * 1320 / ($radius * $radius);
		printf(" %f %f", $sum{$where}{2}{$radius} * $scale, $sum{$where}{58}{$radius} * $scale);
		printf(" %d", $count{$where}{$radius});
	}

	printf("\n");
}
